package com.shoppy.shopkart.models

data class MAttendance(
    var id: String? = null,
    var name: String? = null,
    var email: String? = null,
    var phone_no: String? = null,
    var address: String? = null,
    var salary: Int? = null,
    var day01: String? = null,
    var day02: String? = null,
    var day03: String? = null,
    var day04: String? = null,
    var day05: String? = null,
    var day06: String? = null,
    var day07: String? = null,
    var day08: String? = null,
    var day09: String? = null,
    var day10: String? = null,
    var day11: String? = null,
    var day12: String? = null,
    var day13: String? = null,
    var day14: String? = null,
    var day15: String? = null,
    var day16: String? = null,
    var day17: String? = null,
    var day18: String? = null,
    var day19: String? = null,
    var day20: String? = null,
    var day21: String? = null,
    var day22: String? = null,
    var day23: String? = null,
    var day24: String? = null,
    var day25: String? = null,
    var day26: String? = null,
    var day27: String? = null,
    var day28: String? = null,
    var day29: String? = null,
    var day30: String? = null,
    var day31: String? = null,
){
    fun convertToMap(): MutableMap<String,Any>{
        return mutableMapOf(
            "id" to this.id!!,
            "name" to this.name!!,
            "email" to this.email!!,
            "phone_no" to this.phone_no!!,
            "address" to this.address!!,
            "day01" to this.day01!!,
            "day02" to this.day02!!,
            "day03" to this.day03!!,
            "day04" to this.day04!!,
            "day05" to this.day05!!,
            "day06" to this.day06!!,
            "day07" to this.day07!!,
            "day08" to this.day08!!,
            "day09" to this.day09!!,
            "day10" to this.day10!!,
            "day11" to this.day11!!,
            "day12" to this.day12!!,
            "day13" to this.day13!!,
            "day14" to this.day14!!,
            "day15" to this.day15!!,
            "day16" to this.day16!!,
            "day17" to this.day17!!,
            "day18" to this.day18!!,
            "day19" to this.day19!!,
            "day20" to this.day20!!,
            "day21" to this.day21!!,
            "day22" to this.day22!!,
            "day23" to this.day23!!,
            "day24" to this.day24!!,
            "day25" to this.day25!!,
            "day26" to this.day26!!,
            "day27" to this.day27!!,
            "day28" to this.day28!!,
            "day29" to this.day29!!,
            "day30" to this.day30!!,
            "day31" to this.day31!!,
        )
    }
}
